language: node_js
node_js:
- '0.10'
after_success: 
- sh ./scripts/deploy.sh
notifications:
  slack:
    secure: B678FKsBm6x5qt0cN5kW0tS88ImAXr0SSRu09g1kuJwMG8Q5LoR9tXYKItH6KaQcFYMYrZRitf43UcoD5DHvpqkMDjn7l01yDPLHiazTJu480FNDrLp+jvN80AhAE4dZXCTn0arohr7HYLaaI/ZMRnnCSCOJ3MAGJG7r22UEpJ4=
